data_root=""
CUDA_VISIBLE_DEVICES=1 python main.py --data_root $data_root \
                --experiment_name OPEN_MMD_CAM_RES \
                --pretrained TRUE \
                --num_val_sample_per_class 0 \
                --large_feature_map False \
                --batch_size 32 \
                --epochs 10 \
                --lr 1E-3 \
                --lr_decay_frequency 3 \
                --weight_decay 1.00E-04 \
                --override_cache FALSE \
                --workers 16 \
                --box_v2_metric True \
                --iou_threshold_list 30 50 70 \
                --eval_checkpoint_type last \
                --has_grid_size 111 \
                --has_drop_rate 0.19 \
                --cutmix_beta 1.35 \
                --cutmix_prob 0.34 \
                --adl_threshold 0.99 \
                --adl_drop_rate 0.59 \
                --save_dir 'test_logs' \
                --seed 4 \
                --dataset_name OpenImages \
                --architecture resnet50 \
                --wsol_method cam \
                --uda_method mmd \
                --beta 0.2 \
                --univer 3 \
                --start_epoch 0 \
                --check_path "train_logs/OPEN_MMD_CAM_RES/7_checkpoint.pth.tar" \
                --mode "test"
